"""create invoices, invoice_line_items, exchange_rates, ocr_corrections, validation_results tables

Revision ID: 107942078da9
Revises: 1d22fa5affdc
Create Date: 2026-03-16 14:04:47.353426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '107942078da9'
down_revision: Union[str, None] = '1d22fa5affdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_currency', sa.String(length=10), nullable=False),
    sa.Column('to_currency', sa.String(length=10), nullable=False),
    sa.Column('rate', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('source', sa.Enum('AUTO_API', 'MANUAL', name='exchange_rate_source'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='NULL = auto fetch'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_currency', 'to_currency', 'rate_date', name='uq_exchange_rate_pair_date')
    )
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('invoice_type_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('amount_subtotal', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('amount_tax', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('amount_total', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('currency_original', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('amount_original', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('exchange_rate_id', sa.UUID(), nullable=True),
    sa.Column('po_number', sa.String(length=100), nullable=True),
    sa.Column('po_id', sa.UUID(), nullable=True),
    sa.Column('source_channel', sa.Enum('UPLOAD', 'GMAIL', 'OUTLOOK', 'MANUAL', name='source_channel'), nullable=False),
    sa.Column('source_email', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('ocr_status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'CORRECTED', name='ocr_status'), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'OCR_REVIEW', 'PENDING', 'SUBMITTED', 'REVIEW_NEEDED', 'IN_APPROVAL', 'APPROVED', 'REJECTED', 'SCHEDULED', 'PAID', 'VOID', name='invoice_status'), server_default='RECEIVED', nullable=False),
    sa.Column('validation_status', sa.Enum('PENDING', 'PASS', 'FAIL', 'WARNING', 'OVERRIDDEN', name='validation_status'), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('submission_round', sa.Integer(), server_default='1', nullable=False, comment='제출 횟수 (최초 1, 재제출마다 +1)'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_type_id'], ['invoice_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_company_id'), 'invoices', ['company_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_type_id'), 'invoices', ['invoice_type_id'], unique=False)
    op.create_index(op.f('ix_invoices_vendor_id'), 'invoices', ['vendor_id'], unique=False)
    op.create_table('invoice_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('po_line_id', sa.UUID(), nullable=True),
    sa.Column('matched_contract_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_variance_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_rate_id', sa.UUID(), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['po_line_id'], ['purchase_order_lines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tax_rate_id'], ['tax_rates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_line_items_invoice_id'), 'invoice_line_items', ['invoice_id'], unique=False)
    op.create_table('ocr_corrections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('ocr_value', sa.Text(), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=True),
    sa.Column('corrected_by', sa.UUID(), nullable=True),
    sa.Column('corrected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['corrected_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_corrections_company_id'), 'ocr_corrections', ['company_id'], unique=False)
    op.create_index(op.f('ix_ocr_corrections_invoice_id'), 'ocr_corrections', ['invoice_id'], unique=False)
    op.create_table('validation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('submission_round', sa.Integer(), server_default='1', nullable=False),
    sa.Column('layer', sa.Enum('GLOBAL', 'TYPE', 'CONTRACT', name='validation_layer'), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=True, comment='원본 규칙 ID (참고용)'),
    sa.Column('rule_table', sa.String(length=50), nullable=True, comment='FK 대상 테이블명'),
    sa.Column('rule_name', sa.String(length=255), nullable=True),
    sa.Column('condition_name', sa.String(length=255), nullable=True),
    sa.Column('result', sa.Enum('PASS', 'FAIL', 'WARNING', 'OVERRIDDEN', name='validation_result_status'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('override_by', sa.UUID(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['override_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_company_id'), 'validation_results', ['company_id'], unique=False)
    op.create_index(op.f('ix_validation_results_invoice_id'), 'validation_results', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_results_invoice_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_company_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_ocr_corrections_invoice_id'), table_name='ocr_corrections')
    op.drop_index(op.f('ix_ocr_corrections_company_id'), table_name='ocr_corrections')
    op.drop_table('ocr_corrections')
    op.drop_index(op.f('ix_invoice_line_items_invoice_id'), table_name='invoice_line_items')
    op.drop_table('invoice_line_items')
    op.drop_index(op.f('ix_invoices_vendor_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_type_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_company_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
