"""create vendors and vendor_contracts tables

Revision ID: 1a089efec14c
Revises: cb2dc3dd188c
Create Date: 2026-03-16 01:29:24.753261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a089efec14c'
down_revision: Union[str, None] = 'cb2dc3dd188c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True, comment='NULL = shared pool'),
    sa.Column('vendor_code', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('dba', sa.String(length=255), nullable=True),
    sa.Column('ein', sa.String(length=20), nullable=True),
    sa.Column('ein_normalized', sa.String(length=20), nullable=True, comment='하이픈/공백 제거된 EIN'),
    sa.Column('w9_submitted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('w9_file_path', sa.String(length=500), nullable=True),
    sa.Column('is_1099_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_tax_exempt', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('tax_exempt_cert_path', sa.String(length=500), nullable=True),
    sa.Column('tax_exempt_expiry_date', sa.Date(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('vendor_category', sa.Enum('SERVICE', 'PRODUCT', 'BOTH', name='vendor_category'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='vendor_status'), server_default='ACTIVE', nullable=False),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('billing_city', sa.String(length=100), nullable=True),
    sa.Column('billing_state', sa.String(length=50), nullable=True),
    sa.Column('billing_zip', sa.String(length=20), nullable=True),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('shipping_city', sa.String(length=100), nullable=True),
    sa.Column('shipping_state', sa.String(length=50), nullable=True),
    sa.Column('shipping_zip', sa.String(length=20), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('payment_terms', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('ach_routing', sa.String(length=500), nullable=True, comment='Encrypted (AES-256)'),
    sa.Column('ach_account', sa.String(length=500), nullable=True, comment='Encrypted (AES-256)'),
    sa.Column('internal_buyer', sa.String(length=255), nullable=True, comment='사내 담당 구매자 (free text)'),
    sa.Column('approved_by', sa.String(length=255), nullable=True, comment='벤더 등록 승인자 (free text)'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_company_id'), 'vendors', ['company_id'], unique=False)
    op.create_index(op.f('ix_vendors_ein_normalized'), 'vendors', ['ein_normalized'], unique=False)
    op.create_table('vendor_contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('invoice_type_id', sa.UUID(), nullable=True, comment='NULL = all invoice types'),
    sa.Column('contract_name', sa.String(length=255), nullable=False),
    sa.Column('contract_number', sa.String(length=100), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('expiry_warning_days', sa.Integer(), server_default='30', nullable=False),
    sa.Column('max_order_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('allowed_categories', sa.Text(), nullable=True),
    sa.Column('contracted_prices', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Item → unit price mapping'),
    sa.Column('price_tolerance_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_contracts_company_id'), 'vendor_contracts', ['company_id'], unique=False)
    op.create_index(op.f('ix_vendor_contracts_vendor_id'), 'vendor_contracts', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_contracts_vendor_id'), table_name='vendor_contracts')
    op.drop_index(op.f('ix_vendor_contracts_company_id'), table_name='vendor_contracts')
    op.drop_table('vendor_contracts')
    op.drop_index(op.f('ix_vendors_ein_normalized'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_company_id'), table_name='vendors')
    op.drop_table('vendors')
    # ### end Alembic commands ###
