"""create invoice_types, global_validation_rules, type_rule_sets, type_rule_conditions tables

Revision ID: 1d22fa5affdc
Revises: f82135094b56
Create Date: 2026-03-16 13:38:40.484149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d22fa5affdc'
down_revision: Union[str, None] = 'f82135094b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True, comment='NULL = system default'),
    sa.Column('type_code', sa.String(length=50), nullable=False),
    sa.Column('type_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requires_po', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('requires_approver', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_types_company_id'), 'invoice_types', ['company_id'], unique=False)
    op.create_table('global_validation_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True, comment='NULL = system template'),
    sa.Column('parent_rule_id', sa.UUID(), nullable=True, comment='Inherited from parent rule'),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.Enum('MAX_AMOUNT', 'PAYMENT_TERMS', 'REQUIRED_DOC', 'DUPLICATE_CHECK', 'DUE_DATE', 'ANNUAL_LIMIT', name='global_rule_type'), nullable=False),
    sa.Column('severity', sa.Enum('FAIL', 'WARNING', name='rule_severity'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Rule-type specific config values'),
    sa.Column('apply_to_category', sa.String(length=100), nullable=True, comment='NULL = all categories'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_rule_id'], ['global_validation_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_validation_rules_company_id'), 'global_validation_rules', ['company_id'], unique=False)
    op.create_table('type_rule_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True, comment='NULL = system template'),
    sa.Column('invoice_type_id', sa.UUID(), nullable=False),
    sa.Column('parent_rule_set_id', sa.UUID(), nullable=True, comment='Inherited from parent rule set'),
    sa.Column('rule_set_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_type_id'], ['invoice_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_rule_set_id'], ['type_rule_sets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_rule_sets_company_id'), 'type_rule_sets', ['company_id'], unique=False)
    op.create_index(op.f('ix_type_rule_sets_invoice_type_id'), 'type_rule_sets', ['invoice_type_id'], unique=False)
    op.create_table('type_rule_conditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_set_id', sa.UUID(), nullable=False),
    sa.Column('condition_name', sa.String(length=255), nullable=False),
    sa.Column('condition_type', sa.Enum('AMOUNT_MATCH', 'RATE_CHECK', 'CYCLE_CHECK', 'VARIANCE_CHECK', 'ROUTE_CHECK', 'DELIVERABLE_CHECK', 'HOURLY_RATE_CHECK', 'REQUIRES_APPROVER', name='condition_type'), nullable=False),
    sa.Column('severity', sa.Enum('FAIL', 'WARNING', name='condition_severity'), nullable=False),
    sa.Column('operator', sa.Enum('EQ', 'NEQ', 'GT', 'LT', 'GTE', 'LTE', 'IN', 'BETWEEN', 'PCT_VARIANCE', name='condition_operator'), nullable=False),
    sa.Column('threshold_value', sa.String(length=255), nullable=True),
    sa.Column('threshold_value2', sa.String(length=255), nullable=True, comment='For BETWEEN operator'),
    sa.Column('field_target', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_set_id'], ['type_rule_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_rule_conditions_rule_set_id'), 'type_rule_conditions', ['rule_set_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_type_rule_conditions_rule_set_id'), table_name='type_rule_conditions')
    op.drop_table('type_rule_conditions')
    op.drop_index(op.f('ix_type_rule_sets_invoice_type_id'), table_name='type_rule_sets')
    op.drop_index(op.f('ix_type_rule_sets_company_id'), table_name='type_rule_sets')
    op.drop_table('type_rule_sets')
    op.drop_index(op.f('ix_global_validation_rules_company_id'), table_name='global_validation_rules')
    op.drop_table('global_validation_rules')
    op.drop_index(op.f('ix_invoice_types_company_id'), table_name='invoice_types')
    op.drop_table('invoice_types')
    # ### end Alembic commands ###
