"""create tax_rates, purchase_orders, purchase_order_lines tables

Revision ID: f82135094b56
Revises: 1a089efec14c
Create Date: 2026-03-16 13:16:15.868850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f82135094b56'
down_revision: Union[str, None] = '1a089efec14c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True, comment='NULL = system default'),
    sa.Column('tax_name', sa.String(length=100), nullable=False),
    sa.Column('tax_type', sa.Enum('FEDERAL', 'STATE_SALES', 'STATE_USE', 'EXEMPT', name='tax_type'), nullable=False),
    sa.Column('state_code', sa.String(length=5), nullable=True, comment='e.g. CA, NY, TX'),
    sa.Column('rate_pct', sa.Numeric(precision=6, scale=4), nullable=False, comment='e.g. 8.2500'),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True, comment='NULL = current rate'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_rates_company_id'), 'tax_rates', ['company_id'], unique=False)
    op.create_index(op.f('ix_tax_rates_state_code'), 'tax_rates', ['state_code'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('po_number', sa.String(length=100), nullable=False, comment='UNIQUE per company_id'),
    sa.Column('po_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount_total', sa.Numeric(precision=12, scale=2), nullable=False, comment='Total PO amount (USD)'),
    sa.Column('amount_invoiced', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False, comment='Total invoiced so far'),
    sa.Column('amount_remaining', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False, comment='Remaining balance'),
    sa.Column('status', sa.Enum('OPEN', 'PARTIALLY_INVOICED', 'FULLY_INVOICED', 'CLOSED', 'CANCELLED', name='po_status'), server_default='OPEN', nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'po_number', name='uq_po_company_number')
    )
    op.create_index(op.f('ix_purchase_orders_company_id'), 'purchase_orders', ['company_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_vendor_id'), 'purchase_orders', ['vendor_id'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('po_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False, comment='Ordered quantity'),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False, comment='Agreed unit price (USD)'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Line total (USD)'),
    sa.Column('quantity_invoiced', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False, comment='Qty invoiced so far'),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_lines_po_id'), 'purchase_order_lines', ['po_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_order_lines_po_id'), table_name='purchase_order_lines')
    op.drop_table('purchase_order_lines')
    op.drop_index(op.f('ix_purchase_orders_vendor_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_company_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_tax_rates_state_code'), table_name='tax_rates')
    op.drop_index(op.f('ix_tax_rates_company_id'), table_name='tax_rates')
    op.drop_table('tax_rates')
    # ### end Alembic commands ###
